In [1]:
import pandas as pd
import numpy as np

In [2]:
from IPython.display import display_html
from itertools import chain,cycle
def display_side_by_side(*args,titles=cycle([''])):
    html_str=''
    for df,title in zip(args, chain(titles,cycle(['</br>'])) ):
        html_str+='<th style="text-align:center"><td style="vertical-align:top">'
        html_str+=f'<h2 style="text-align: center;">{title}</h2>'
        html_str+=df.to_html().replace('table','table style="display:inline"')
        html_str+='</td></th>'
    display_html(html_str,raw=True)

In [3]:
seq = np.arange(20). reshape(4, 5)
seq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
np.concatenate([seq, seq], axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [6]:
np.concatenate([seq, seq], axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
data1 = pd.Series(
    [0, 1], index=['a', 'b'])
data2 = pd.Series(
    [2,3,4], index=['c','d','e'])
data3 = pd.Series(
    [5, 6], index=['f', 'g'])

In [8]:
display(data1, data2, data3)

a    0
b    1
dtype: int64

c    2
d    3
e    4
dtype: int64

f    5
g    6
dtype: int64

In [9]:
pd.concat([data1, data2, data3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [10]:
pd.concat([data1, data2, data3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [11]:
pd.concat([data1, data2, data3], axis=1, join='inner')

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [12]:
data4= pd.Series([10,11,12], 
                 index=['a','b',"c"])
data4

a    10
b    11
c    12
dtype: int64

In [13]:
data1

a    0
b    1
dtype: int64

In [14]:
pd.concat([data1, data4], axis=1, join='inner')

0   1
a  0  10
b  1  11

In [15]:
pd.concat([data1, data4], axis=1, join='inner', keys=['d1', 'd2'])

d1  d2
a   0  10
b   1  11

In [16]:
pd.concat([data1, data4], axis=1, join='inner', keys = 'a')

a
a  0
b  1

In [17]:
pd.concat([data1, data4], axis=1, join='inner', keys = 'b')

b
a  0
b  1

In [18]:
display(data1, data4)

a    0
b    1
dtype: int64

a    10
b    11
c    12
dtype: int64

In [19]:
pd.concat([data1, data4], axis=0, join='inner')

a     0
b     1
a    10
b    11
c    12
dtype: int64

In [20]:
pd.concat([data1, data4], axis=0, join='inner', keys=['d1', 'd2'])

d1  a     0
    b     1
d2  a    10
    b    11
    c    12
dtype: int64

In [21]:
display(data1, data2, data4)

a    0
b    1
dtype: int64

c    2
d    3
e    4
dtype: int64

a    10
b    11
c    12
dtype: int64

In [22]:
pd.concat([data1, data2, data4], 
            keys=['one', 'two','three'])

one    a     0
       b     1
two    c     2
       d     3
       e     4
three  a    10
       b    11
       c    12
dtype: int64

In [23]:
pd.concat([data1, data2, data4], 
            axis=1,
            keys=['one', 'two', 'three'])

one  two  three
a  0.0  NaN   10.0
b  1.0  NaN   11.0
c  NaN  2.0   12.0
d  NaN  3.0    NaN
e  NaN  4.0    NaN

In [24]:
df1 = pd.DataFrame(
    np.arange(6).reshape(3, 2),
    index=['a', 'b', 'c'],
    columns=['one', 'two'])
df2 = pd.DataFrame(
    10+np.arange(4).reshape(2,2),
    index=['a', 'c'],
    columns=['three', 'four'])

In [25]:
display_side_by_side(df1, df2)

one 
 two 
 
 
 
 
 a 
 0 
 1 
 
 
 b 
 2 
 3 
 
 
 c 
 4 
 5 
 
 
 
 
 
 
 three 
 four 
 
 
 
 
 a 
 10 
 11 
 
 
 c 
 12 
 13

In [26]:
pd.concat([df1, df2])

one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN   10.0  11.0
c  NaN  NaN   12.0  13.0

In [27]:
pd.concat([df1, df2], axis=1)

one  two  three  four
a    0    1   10.0  11.0
b    2    3    NaN   NaN
c    4    5   12.0  13.0

In [28]:
pd.concat([df1, df2], axis=1, join='inner')

one  two  three  four
a    0    1     10    11
c    4    5     12    13

In [29]:
pd.concat([df1, df2], axis=1, keys=['s1', 's2'])

s1        s2      
  one two three  four
a   0   1  10.0  11.0
b   2   3   NaN   NaN
c   4   5  12.0  13.0

In [30]:
data1 = pd.DataFrame(
    np.random.randn(3, 4),
    columns=['a','b','c','d'])
data2 = pd.DataFrame(
    np.random.randn(2, 3),
    columns=['b','d','a'])

In [31]:
display_side_by_side(data1, data2)

a 
 b 
 c 
 d 
 
 
 
 
 0 
 -1.593936 
 1.915522 
 -1.171363 
 -0.034515 
 
 
 1 
 -0.573494 
 0.265495 
 1.360683 
 1.480692 
 
 
 2 
 -0.365692 
 -0.679544 
 0.418238 
 -0.907907 
 
 
 
 
 
 
 b 
 d 
 a 
 
 
 
 
 0 
 -0.736389 
 -0.194004 
 -0.615672 
 
 
 1 
 0.869787 
 -0.416228 
 -0.368709

In [33]:
pd.concat([data1, data2])

a         b         c         d
0 -1.593936  1.915522 -1.171363 -0.034515
1 -0.573494  0.265495  1.360683  1.480692
2 -0.365692 -0.679544  0.418238 -0.907907
0 -0.615672 -0.736389       NaN -0.194004
1 -0.368709  0.869787       NaN -0.416228

In [35]:
pd.concat([data1, data2], ignore_index=True)

a         b         c         d
0 -1.593936  1.915522 -1.171363 -0.034515
1 -0.573494  0.265495  1.360683  1.480692
2 -0.365692 -0.679544  0.418238 -0.907907
3 -0.615672 -0.736389       NaN -0.194004
4 -0.368709  0.869787       NaN -0.416228

In [38]:
pd.concat([data1, data2], axis=1, join='inner')

a         b         c         d         b         d         a
0 -1.593936  1.915522 -1.171363 -0.034515 -0.736389 -0.194004 -0.615672
1 -0.573494  0.265495  1.360683  1.480692  0.869787 -0.416228 -0.368709