In [16]:
import pandas as pd; import numpy as np

In [45]:
np.random.seed(10)
data = np.random.randint(1,100, 1000)
data

array([10, 16, 65, 29, 90, 94, 30,  9, 74,  1, 41, 37, 17, 12, 55, 89, 63,
       34, 73, 79, 50, 52, 55, 78, 70, 14, 26, 14, 93, 87, 31, 31, 90, 13,
       66, 32, 58, 37, 28, 19, 94, 78, 23, 24, 95, 12, 29, 75, 89, 10, 16,
       19, 81, 72, 89, 12, 18, 47,  8, 76, 29, 34, 85, 97, 89, 45,  6,  5,
       72, 89, 89, 51, 55, 35, 16, 78, 89, 16,  7, 86, 23, 12, 13, 93, 97,
       63, 58, 80, 43, 58, 98, 51, 46, 41, 90, 74, 38,  1, 19, 24,  4, 30,
       17, 85, 83, 15, 52, 80, 18, 51, 54, 26, 49, 18, 33, 82, 81, 42, 91,
       13, 31, 82, 18, 17,  1, 32, 74, 65, 39, 23, 97, 67, 68, 63, 96, 28,
       83, 63, 78, 49, 94, 76, 87, 38, 12, 22, 34, 96, 44, 89, 97, 74, 41,
       44, 91, 72,  9, 86, 73, 29, 31, 90, 26, 79, 82, 86, 63, 14, 42, 34,
        5, 88, 95, 29, 40, 92, 10,  8, 23, 33,  4, 10, 53, 77, 69, 31, 71,
       75, 31, 10,  3, 66, 14, 76, 53,  6, 94, 85, 49, 63, 43, 35, 41, 47,
       33, 95, 87, 59, 70, 46, 19, 51, 45,  2, 64, 78, 19, 28, 84, 38, 72,
       89, 16, 56,  7, 45

In [46]:
interval = pd.cut(data, 4, precision=3)
interval

[(0.902, 25.5], (0.902, 25.5], (50.0, 74.5], (25.5, 50.0], (74.5, 99.0], ..., (25.5, 50.0], (50.0, 74.5], (74.5, 99.0], (0.902, 25.5], (50.0, 74.5]]
Length: 1000
Categories (4, interval[float64, right]): [(0.902, 25.5] < (25.5, 50.0] < (50.0, 74.5] < (74.5, 99.0]]

In [47]:
type(interval)

pandas.core.arrays.categorical.Categorical

In [48]:
interval = pd.qcut(data, 4, labels=['Q1', "Q2", "Q3", "Q4"])
interval

['Q1', 'Q1', 'Q3', 'Q2', 'Q4', ..., 'Q2', 'Q3', 'Q4', 'Q1', 'Q3']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [49]:
interval = pd.Series(interval, name='quarter')
interval

0      Q1
1      Q1
2      Q3
3      Q2
4      Q4
       ..
995    Q2
996    Q3
997    Q4
998    Q1
999    Q3
Name: quarter, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [51]:
pd.Series(data)

0      10
1      16
2      65
3      29
4      90
       ..
995    48
996    71
997    94
998     8
999    60
Length: 1000, dtype: int32

In [36]:
pd.Series(data).groupby(interval).agg(['count', 'min', 'max'])

count  min  max
quarter                 
Q1         256    1   24
Q2         250   25   50
Q3         244   51   75
Q4         250   76   99

In [38]:
pd.Series(data).groupby(interval).agg(['count', 'min', 'max']).reset_index()

quarter  count  min  max
0      Q1    256    1   24
1      Q2    250   25   50
2      Q3    244   51   75
3      Q4    250   76   99

In [69]:
data

array([10, 16, 65, 29, 90, 94, 30,  9, 74,  1, 41, 37, 17, 12, 55, 89, 63,
       34, 73, 79, 50, 52, 55, 78, 70, 14, 26, 14, 93, 87, 31, 31, 90, 13,
       66, 32, 58, 37, 28, 19, 94, 78, 23, 24, 95, 12, 29, 75, 89, 10, 16,
       19, 81, 72, 89, 12, 18, 47,  8, 76, 29, 34, 85, 97, 89, 45,  6,  5,
       72, 89, 89, 51, 55, 35, 16, 78, 89, 16,  7, 86, 23, 12, 13, 93, 97,
       63, 58, 80, 43, 58, 98, 51, 46, 41, 90, 74, 38,  1, 19, 24,  4, 30,
       17, 85, 83, 15, 52, 80, 18, 51, 54, 26, 49, 18, 33, 82, 81, 42, 91,
       13, 31, 82, 18, 17,  1, 32, 74, 65, 39, 23, 97, 67, 68, 63, 96, 28,
       83, 63, 78, 49, 94, 76, 87, 38, 12, 22, 34, 96, 44, 89, 97, 74, 41,
       44, 91, 72,  9, 86, 73, 29, 31, 90, 26, 79, 82, 86, 63, 14, 42, 34,
        5, 88, 95, 29, 40, 92, 10,  8, 23, 33,  4, 10, 53, 77, 69, 31, 71,
       75, 31, 10,  3, 66, 14, 76, 53,  6, 94, 85, 49, 63, 43, 35, 41, 47,
       33, 95, 87, 59, 70, 46, 19, 51, 45,  2, 64, 78, 19, 28, 84, 38, 72,
       89, 16, 56,  7, 45

In [70]:
df = pd.DataFrame({'score': data})
df

score
0       10
1       16
2       65
3       29
4       90
..     ...
995     48
996     71
997     94
998      8
999     60

[1000 rows x 1 columns]

In [72]:
df['quar'] = pd.qcut(x=df['score'], q=4, labels=['Q1', "Q2", "Q3", "Q4"])

In [73]:
df

score quar
0       10   Q1
1       16   Q1
2       65   Q3
3       29   Q2
4       90   Q4
..     ...  ...
995     48   Q2
996     71   Q3
997     94   Q4
998      8   Q1
999     60   Q3

[1000 rows x 2 columns]

In [80]:
df.groupby('quar').agg(['count', 'sum', 'max', 'min']).reset_index()

quar score               
       count    sum max min
0   Q1   256   3157  24   1
1   Q2   250   9363  50  25
2   Q3   244  15471  75  51
3   Q4   250  21928  99  76

In [82]:
N=10000000
np.random.seed(123)
num=pd.Series(np.random.randn(N))
num

0         -1.085631
1          0.997345
2          0.282978
3         -1.506295
4         -0.578600
             ...   
9999995    0.657336
9999996    0.823554
9999997   -0.528144
9999998    0.084826
9999999    0.922815
Length: 10000000, dtype: float64

In [88]:
label = pd.Series(['a', 'b', 'c', 'd']*(N//4))
label

0          a
1          b
2          c
3          d
4          a
          ..
9999995    d
9999996    a
9999997    b
9999998    c
9999999    d
Length: 10000000, dtype: object

In [90]:
cat=label.astype("category")
cat

0          a
1          b
2          c
3          d
4          a
          ..
9999995    d
9999996    a
9999997    b
9999998    c
9999999    d
Length: 10000000, dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [91]:
label.memory_usage()

80000132

In [92]:
cat.memory_usage()

10000336

In [94]:
coefficient = label.memory_usage() / cat.memory_usage()
coefficient

7.999744408587872

In [133]:
ser=pd.Series(["a","b","c","d"]*2)
ser

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [134]:
ser_cat = pd.Categorical(values=ser)
ser_cat

['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']
Categories (4, object): ['a', 'b', 'c', 'd']

In [135]:
ser=pd.Series(["a","b","c","d"]*2)
ser

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [136]:
ser_cat = ser.astype('category')
ser_cat

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [137]:
ser_cat.cat

In [138]:
ser_cat.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [139]:
ser_cat.values

['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']
Categories (4, object): ['a', 'b', 'c', 'd']

In [140]:
ser_cat.values.codes

array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int8)

In [141]:
ser_cat.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [142]:
ser_cat.values.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [146]:
new_cat=["a","b","c","d","e"]

In [147]:
ser_cat.cat.set_categories(new_cat)

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [173]:
(ser_cat == 'a') | (ser_cat =='b')

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7    False
dtype: bool

In [174]:
ser_cat.isin(['a', 'b'])

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7    False
dtype: bool

In [176]:
ser_cat[ser_cat.isin(['a', 'b'])]

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [177]:
ser2_cat = ser_cat[ser_cat.isin(['a', 'b'])]
ser2_cat

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [178]:
ser2_cat.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [190]:
ser_cat

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [191]:
pd.get_dummies(ser_cat)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True

In [193]:
pd.get_dummies(ser_cat, dtype=int)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [194]:
games = pd.read_csv(r'C:\Users\dell\Desktop\img\vgsalesGlobale.csv')
games

Rank                           Name         Platform  Year    Genre  \
0       1  Syrup - Monin - Passion Fruit  Nintendo Switch  2008   Action   
1       2                           Yams  Nintendo Switch  2010   Sports   
2       3                  Pepsi, 355 Ml              PS4  1985   Sports   
3       4                        Gherkin         Xbox One  2016   Action   
4       5  Pastry - French Mini Assorted  Nintendo Switch  2020  Shooter   
..    ...                            ...              ...   ...      ...   
995   996     Shrimp - Black Tiger 16/20         Xbox One  1985   Sports   
996   997     Muffin Mix - Morning Glory         Xbox One  2011  Shooter   
997   998       Muffin Orange Individual              PS4  1996   Action   
998   999                  Sage - Ground              PS4  1997   Sports   
999  1000          Cheese - Swiss Sliced         Xbox One  1996   Action   

      Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0      Devshare     82.51     20.44      8.39        10.16          7.01  
1          Muxo      7.43      8.40      9.66         3.07          6.33  
2         Eidel     17.50     17.96      7.15         4.74          5.63  
3         Mynte     13.05      5.60      5.64         6.97          1.23  
4         Quinu     16.92     24.00      5.59         5.16          3.66  
..          ...       ...       ...       ...          ...           ...  
995    Edgewire     77.09      3.36      0.69        10.33          0.34  
996       Skyba      5.14      8.72      4.02         7.42          8.20  
997  Topicstorm     19.89     27.42      4.02         4.12          0.65  
998  Jabbertype     38.59      7.22      6.20         3.71          0.09  
999      Voonyx     58.61     21.83      5.89         2.65          0.50  

[1000 rows x 11 columns]

In [195]:
games['Genre'] = games['Genre'].astype('category')
games['Genre']

0       Action
1       Sports
2       Sports
3       Action
4      Shooter
        ...   
995     Sports
996    Shooter
997     Action
998     Sports
999     Action
Name: Genre, Length: 1000, dtype: category
Categories (3, object): ['Action', 'Shooter', 'Sports']

In [196]:
games['Genre'] = pd.Categorical(games['Genre'])
games['Genre']

0       Action
1       Sports
2       Sports
3       Action
4      Shooter
        ...   
995     Sports
996    Shooter
997     Action
998     Sports
999     Action
Name: Genre, Length: 1000, dtype: category
Categories (3, object): ['Action', 'Shooter', 'Sports']